# include <ioStream>

using namespace std;

int main(){

    // // limits and 
    // int a;
    // cout<<&a<<endl;
    // cout<<numeric_limits<int>::max()<<endl;
    // cout<<(numeric_limits<char>::min())<<endl;
    // cout<<static_cast<int>(numeric_limits<char>::min())<<endl;
    // cout<<sizeof(int);
 


//   int a=20,b=25;
// //  arthmetic operation
//  cout<<a*b<<" ";
//  cout<<a/b<<" ";
//  cout<<a%b<<" ";
// // relational operation
// cout<< (a<b)<<" ";
// cout<< (a>b)<<" ";
// cout<< (a<=b)<<" ";
// cout<< (a>=b)<<" ";
// cout<<(a!=b)<<" ";
// int pass;
// cin>>pass;

// (pass==5555)?cout<<"divisible by both":cout<<"not divide";


//     int passward;
//     cout<<"enter passward";
//     cin>>passward;
//     (passward==1234)?cout<<"open":cout<<"wrong passward try again",
//     cin>>passward;
//     (passward==1234)?cout<<"open":cout<<"wrong passward try again",
//     cin>>passward;
//    (passward==1234)?cout<<"open":cout<<"your card has been blocked";
    
    // int passward;
    // cout<<"enter passward";
    // cin>>passward;
    // if(passward==1111){
    //     cout<<"open";
    // }else{
    //     cout<<"wrong passward try again";
    //     cin>>passward;
    //     if(passward==1111){
    //         cout<<"open";
    //         }else{
    //             cout<<"wrang passward try again";
    //             cin>>passward;
                
    //             if(passward==1111){
    //                 cout<<"open";
    //                 }else{
    //                     cout<<"your card has been blocked";
    //             }
    //         }
    // }
 


//  int a =20,b=30,c=35;
  
//  int press;
// cin>>press;

// if(press ==1){
//     int a =20,b=10;
//     a=a+b;
//     b=a-b;
//     a=a-b;
//     cout<<a<<b;
// }else if(press ==2){

//     int a=30,b=20,c=35;
//     a=a+b+c;
//     b=a-b-c;
//     c=a-c;
//     cout <<a<<b<<c;


// }

// string press;
// cout<<"enter season";
// cin>> press;
// if(press=="summer"){
//     cout<<"this is summer season";
// }
// else if(press=="winter"){
//     cout<<"this is winter season";
// }
// else if(press=="rainy"){
//     cout<<"this is rainy season";
// }
// else if(press=="autumn"){
//     cout<<"this is autumn season";
// }
// else{
//     cout<<"invalid input";
// }

// string press;
// int amount;
// cout<<"ask me anything, choose these product or servise"<<endl;

// cin>>press;

// if(press=="product"){
//     cout<<"1.home loan or 2.car loan"<<endl;
//     string press1;
//     cin>>press1;
//     if(press1=="home"){
//         cout<<"home loan alloted upto 5L " <<endl   ;
//         cin>>amount;
//         cout<<amount<<endl;
//          if(amount>=100000&&amount<=500000){
//             cout<<"your loan is alloted  "<<endl << amount << " "<<endl;

//         }else{
//             cout<<"invalide input"<<endl;
//         }

//     }else if(press1=="car"){
//         cout<<"car loan alloted upto 10L"<<endl;
//         cin>>amount;
//         cout<<amount<<endl;
//          if(amount>=100000&&amount<=1000000){
//             cout<<"your loan is alloted";

//         }else{
//             cout<<"invalide input";
//         }

//     }

// }else if (press =="service")
// {
//     cout<<"service is close";
// }

// else{
//   cout<<"invalide input";
// }

// string a;
// cin>>a;
// if(a=="askriya"){
//     cout<<"choose these product or service";
//     cin>>a;
//     if(a=="product"){
//         cout<<"home loan or car loan"<<endl;
//         cin>>a;
//         if(a=="home"){
//             cout<<"home loan alloted upto 5L "<<endl;
//         }
//         else if(a=="car"){
//             cout<<"car loan alloted upto 10L "<<endl;
//         }


//     }else if(a=="service"){
//         cout<<"service is close"<<endl;
//     }

// }
// else{
//     cout<<"invalide input";
// }

}